//
//  Constants.swift
//  Ride Tracker
//
//  Created by Gabriel Revells on 9/27/18.
//  Copyright © 2018 Gabriel Revells. All rights reserved.
//

import UIKit

// Segue names
let SHOW_RIDE_RECORDING = "SHOW_RIDE_RECORDING"
let SHOW_RIDE_WAIT_TIME_COUNTER = "SHOW_RIDE_WAIT_TIME_COUNTER"
let SHOW_EDIT_RIDE_LOG = "SHOW_EDIT_RIDE_LOG"
let SHOW_PARK_LIST_VIEW = "SHOW_PARK_LIST_VIEW"
let UNWIND_TO_RIDE_LIST_VIEW = "UNWIND_TO_RIDE_LIST_VIEW"
let UNWIND_TO_RIDE_DETAIL_VIEW = "UNWIND_TO_RIDE_DETAIL_VIEW"

// Table view cell identifiers
let RIDE_TABLE_VIEW_CELL = "RIDE_TABLE_VIEW_CELL"

let RIDE_COLLECTION_VIEW_CELL = "RIDE_COLLECTION_VIEW_CELL"
let RIDE_MAP_COLLECTION_VIEW_CELL = "RIDE_MAP_COLLECTION_VIEW_CELL"

// User defaults names
let USER_DEFAULTS_SELECTED_PARK = "USER_DEFAULTS_SELECTED_PARK"
let USER_DEFAULTS_SELECTED_PARK_ID = "USER_DEFAULTS_SELECTED_PARK_ID"
let USER_DEFAULTS_CURRENT_WAIT_RIDE_ID = "USER_DEFAULTS_CURRENT_WAIT_RIDE_ID"
let USER_DEFAULTS_CURRENT_WAIT_RIDE_NAME = "USER_DEFAULTS_CURRENT_WAIT_RIDE_NAME"
let USER_DEFAULTS_CURRENT_WAIT_START_TIME = "USER_DEFAULTS_CURRENT_WAIT_START_TIME"

let CONTEXT = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext

extension UIColor {
    static var shadow = UIColor(white: 0.466666667, alpha: 1)
}
